ads/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import *

app_name = 'ads'
urlpatterns = [
    path('ads/', AdListView.as_view(), name='index'),
    path('ad/create', AdCreateView.as_view(), name='create'),
    path('ad/<int:pk>/', AdDetailView.as_view(), name='detail'),
    path('ad/<int:pk>/update', AdUpdateView.as_view(), name='update'),
    path('ad/<int:pk>/delete', AdDeleteView.as_view(), name='delete'),
    path('ad_picture/<int:pk>', stream_picture, name='ad_picture'),
    path('ad/<int:pk>/comment', create_comment, name='comment_create'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete')
]

autos/urls.py
from django.urls import path
from .views import *


app_name = 'autos'
urlpatterns = [
    path('', MainView.as_view(), name='all'),
    path('main/create/', AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', MakeView.as_view(), name='make_list'),
    path('lookup/create/', MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', MakeDelete.as_view(), name='make_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/ads/'), name='index'),
    path('', include('ads.urls')),
    path('home/', TemplateView.as_view(template_name='home/main.html'),
        name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Make(models.Model):
    name = models.CharField(
            max_length=200,
            help_text='Enter a make (e.g. Chevrolet)',
            validators=[MinLengthValidator(2, "Make must be greater than 1 character")]
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Auto(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)

    # Shows up in the admin list
    def __str__(self):
        return self.nickname

autos/forms.py
from django.forms import ModelForm

from autos.models import Auto


class AutoForm(ModelForm):
    class Meta:
        model = Auto
        fields = '__all__'

autos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import View, ListView, CreateView, UpdateView, \
    DeleteView

from autos.forms import AutoForm
from autos.models import Make, Auto


class MainView(LoginRequiredMixin, View):
    def get(self, request: HttpRequest):
        make_count = Make.objects.all().count()
        autos = Auto.objects.all()
        return render(request, 'autos/auto_list.html', context={
            'make_count': make_count,
            'auto_list': autos,
        })


class AutoCreate(LoginRequiredMixin, View):
    template = 'autos/auto_form.html'
    success_url = 'autos:all'

    def get(self, request: HttpRequest):
        form = AutoForm()
        return render(request, self.template, {'form': form})

    def post(self, request: HttpRequest):
        form = AutoForm(request.POST)
        if not form.is_valid():
            return render(request, self.template, {'form': form})
        else:
            form.save()
            return redirect(self.success_url)


class AutoUpdate(LoginRequiredMixin, View):
    template = 'autos/auto_form.html'
    success_url = 'autos:all'

    def get(self, request: HttpRequest, pk: int):
        auto = get_object_or_404(Auto, pk=pk)
        form = AutoForm(instance=auto)
        return render(request, self.template, {'form': form})

    def post(self, request: HttpRequest, pk: int):
        auto = get_object_or_404(Auto, pk=pk)
        form = AutoForm(request.POST, instance=auto)
        if not form.is_valid():
            return render(request, self.template, {'form': form})
        else:
            form.save()
            return redirect(self.success_url)


class AutoDelete(LoginRequiredMixin, View):
    success_url = 'autos:all'

    def get(self, request: HttpRequest, pk: int):
        return render(request, 'autos/auto_confirm_delete.html', {
            'auto': get_object_or_404(Auto, pk=pk)
        })

    def post(self, request: HttpRequest, pk: int):
        get_object_or_404(Auto, pk=pk).delete()
        return redirect(self.success_url)


class MakeView(LoginRequiredMixin, ListView):
    model = Make
    template_name = 'make_list.html'


class MakeCreate(LoginRequiredMixin, CreateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:make_list')


class MakeUpdate(LoginRequiredMixin, UpdateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:make_list')


class MakeDelete(LoginRequiredMixin, DeleteView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:make_list')

autos/templates/autos/auto_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Auto{% endblock %}
{% block content %}
<h1>Confirm delete</h1>
<p>Do you really want to delete auto "{{ auto }}"?</p>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel"
         onclick="window.location='{% url 'autos:all' %}';return !1">
</form>
{% endblock content %}

autos/templates/autos/auto_form.html
{% extends 'base.html' %}

{% block title %}Add Auto{% endblock %}
{% block content %}
<h1>Add Auto</h1>
<form method="post">
  {% csrf_token %}
  <table>{{ form.as_table }}</table>
  <input type="submit" value="Submit">
  <input type="submit" value="Cancel"
         onclick="window.location='{% url 'autos:all' %}';return !1">
</form>
{% endblock content %}

autos/templates/autos/auto_list.html
{% extends 'base.html' %}

{% block title %}Auto List{% endblock %}
{% block content %}
<h1>Auto List</h1>
<ul>
  {% for auto in auto_list %}
  <li><p>
    {{ auto.nickname }} ({{ auto.make }})
    (<a href="{% url 'autos:auto_update' auto.id %}">Update</a>
    | <a href="{% url 'autos:auto_delete' auto.id %}">Delete</a>)
    <br />
    {{ auto.comments }} ({{ auto.mileage }} miles)
  </p></li>
  {% empty %}
  There are no autos in the library
  {% endfor %}
</ul>
<p><a href="{% url 'autos:auto_create' %}">Add an auto</a></p>
<p>
  <a href="{% url 'autos:make_list' %}">View makes</a> ({{ make_count }}) |
  <a href="{% url 'autos:make_create' %}">Add a make</a>
</p>
{% endblock content %}

autos/templates/autos/make_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Make{% endblock %}
{% block content %}
<h1>Confirm delete</h1>
<p>Do you really want to delete make "{{ make }}"?</p>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel"
         onclick="window.location='{% url 'autos:make_list' %}';return false">
</form>
{% endblock content %}

autos/templates/autos/make_form.html
{% extends 'base.html' %}

{% block title %}Add Make{% endblock %}
{% block content %}
<h1>Add Make</h1>
<form method="post">
  {% csrf_token %}
  <table>{{ form.as_table }}</table>
  <input type="submit" value="Submit">
  <input type="submit" value="Cancel"
         onclick="window.location='{% url 'autos:make_list' %}';return false">
</form>
{% endblock content %}

autos/templates/autos/make_list.html
{% extends 'base.html' %}

{% block title %}Make list{% endblock %}
{% block content %}
<h1>Make list</h1>
<ul>
  {% for make in make_list %}
  <li>
    {{ make }}
    (<a href="{% url 'autos:make_update' make.id %}">Update</a>
    | <a href="{% url 'autos:make_delete' make.id %}">Delete</a>)
  </li>
  {% empty %}
  No makes yet
  {% endfor %}
</ul>
<p><a href="{% url 'autos:make_create' %}">Add make</a> <a href="{% url 'autos:make_list' %}">View makes</a></p>
<p><a href="{% url 'autos:all' %}">Back to autos</a></p>
{% endblock content %}