ads/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import *

app_name = 'ads'
urlpatterns = [
    path('ads/', AdListView.as_view(), name='index'),
    path('ad/create', AdCreateView.as_view(), name='create'),
    path('ad/<int:pk>/', AdDetailView.as_view(), name='detail'),
    path('ad/<int:pk>/update', AdUpdateView.as_view(), name='update'),
    path('ad/<int:pk>/delete', AdDeleteView.as_view(), name='delete'),
    path('ad_picture/<int:pk>', stream_picture, name='ad_picture'),
    path('ad/<int:pk>/comment', create_comment, name='comment_create'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/ads/'), name='index'),
    path('', include('ads.urls')),
    path('home/', TemplateView.as_view(template_name='home/main.html'),
        name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

polls/urls.py
from django.urls import path
from polls.views import *

app_name = 'polls'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('<int:pk>/results', ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote', vote, name='vote')
]

polls/models.py
from django.contrib.auth import get_user_model
from django.db import models as m
from django.urls import reverse

User = get_user_model()


class Question(m.Model):
    title = m.CharField(max_length=200)
    description = m.TextField()
    author = m.ForeignKey(User, on_delete=m.CASCADE)
    pub_date = m.DateTimeField()
    view_count = m.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('polls:detail', kwargs={'pk': self.id})


class Choice(m.Model):
    question = m.ForeignKey(Question, on_delete=m.CASCADE)
    choice_text = m.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

    def get_vote_count(self):
        l = len(Vote.objects.filter(choice=self))
        print(l)
        return l


class Vote(m.Model):
    question = m.ForeignKey(Question, on_delete=m.CASCADE)
    choice = m.ForeignKey(Choice, on_delete=m.CASCADE)
    user = m.ForeignKey(User, on_delete=m.CASCADE)

polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic as g

from polls.models import Question, Vote, Choice


class IndexView(g.ListView):
    model = Question
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]  # noqa


class DetailView(g.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get(self, request, **kwargs):
        question = self.get_object()
        question.view_count += 1
        question.save()
        return super().get(request, **kwargs)


class VoteRequiredMixin:
    """Mixin checks if user has voted on a question.
    Assuming user is already authenticated
    """
    def dispatch(self, request: HttpRequest, **kwargs):
        question: Question = get_object_or_404(Question, pk=self.kwargs['pk'])
        self.user_choice = Vote.objects.get(
            user=request.user,
            question=question,
        ).choice
        if self.user_choice:
            return super().dispatch(request, **kwargs)
        else:
            return HttpResponseRedirect(question.get_absolute_url())

    def get_context_data(self, **kwargs):
        context = {}
        if self.user_choice:
            context['user_choice'] = self.user_choice
        context.update(kwargs)
        return super().get_context_data(**context)


class ResultsView(LoginRequiredMixin, VoteRequiredMixin, g.DetailView):
    model = Question
    template_name = 'polls/results.html'


def results(request: HttpRequest, question_id: int):
    try:
        user_choice = Vote.objects.get(  # noqa
            user_id=request.user.id,  # noqa
            question_id=question_id
        ).choice_id

    except Vote.DoesNotExist:  # noqa
        request.session['error'] = "You have not voted on the question"  # noqa
        return HttpResponseRedirect(
            reverse('polls:detail', args=(question_id,))
        )

    else:
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/results.html', context={
            'question': question,
            'user_choice': user_choice,
        })


@login_required
def vote(request: HttpRequest, question_id: int):
    question = get_object_or_404(Question, pk=question_id)
    try:
        choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', context={
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        try:
            # user has already voted
            vote = Vote.objects.get(user=request.user, question=question)
            vote.choice = choice
        except Vote.DoesNotExist:
            # else create a vote
            vote = Vote(question=question, choice=choice, user=request.user)
        vote.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
{% extends 'base.html' %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
<h1>{{ question.title }}</h1>
<p>{{ question.description }}</p>
<p>
  published by {{ question.author.username }}
  on {{ question.pub_date }},
  viewed {{ question.view_count }} times
</p>
<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
  <label>
    <input type="radio" name="choice" value="{{ choice.id }}">
    {{ choice.choice_text }}
  </label><br>
  {% endfor %}
  <input type="submit">
</form>
{% endblock content %}

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Index</title>
</head>
<body>
<p>Welcome to polls index</p>
<ul>
  {% for question in latest_question_list %}
  <li><a href="{{ question.get_absolute_url }}">{{ question }}</a></li>
  {% endfor %}
</ul>
</body>
</html>

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %}Results{% endblock %}
{% block css %}<style> .checked { font-weight: bold } </style> {% endblock %}

{% block content %}
<h1>{{ question.title }}</h1>
<p>{{ question.description }}</p>
<p>
  published by {{ question.author.username }}
  on {{ question.pub_date }},
  viewed {{ question.view_count }} times
</p>
<ul>
  {% for choice in question.choice_set.all %}
  {% with vote_count=choice.get_vote_count %}
  <li {% if user_choice == choice %}class="checked" {% endif %}>
    {{ choice.choice_text }} -- {{ vote_count }} vote{{vote_count|pluralize}}
  </li>
  {% endwith %}
  {% endfor %}
</ul>
{% endblock content %}