ads/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import *

app_name = 'ads'
urlpatterns = [
    path('ads/', AdListView.as_view(), name='index'),
    path('ad/create', AdCreateView.as_view(), name='create'),
    path('ad/<int:pk>/', AdDetailView.as_view(), name='detail'),
    path('ad/<int:pk>/update', AdUpdateView.as_view(), name='update'),
    path('ad/<int:pk>/delete', AdDeleteView.as_view(), name='delete'),
    path('ad_picture/<int:pk>', stream_picture, name='ad_picture'),
    path('ad/<int:pk>/comment', create_comment, name='comment_create'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete')
]

cats/urls.py
from django.urls import path
from .views import *


app_name = 'cats'
urlpatterns = [
    path('', CatView.as_view(), name='all'),
    path('', CatView.as_view(), name='cat_list'),
    path('main/create/', CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', CatDelete.as_view(), name='cat_delete'),
    path('lookup/', BreedView.as_view(), name='breed_list'),
    path('lookup/create/', BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', BreedDelete.as_view(), name='breed_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/ads/'), name='index'),
    path('', include('ads.urls')),
    path('home/', TemplateView.as_view(template_name='home/main.html'),
        name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

cats/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class Breed(models.Model):
    name = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Breed must longer than a character")])

    def __str__(self):
        return self.name


class Cat(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Nickname must be longer than a character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=200)
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE)

    def __str__(self):
        return self.nickname

cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from cats.models import Cat, Breed


class CatView(LoginRequiredMixin, ListView):
    model = Cat

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['breed_count'] = Breed.objects.all().count()
        return context


class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:cat_list')


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:cat_list')


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = reverse_lazy('cats:cat_list')


class BreedView(LoginRequiredMixin, ListView):
    model = Breed


class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:breed_list')


class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:breed_list')


class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    success_url = reverse_lazy('cats:breed_list')

cats/templates/cats/breed_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Breed{% endblock %}
{% block content %}
<h1>Confirm delete</h1>
<p>Do you really want to delete breed "{{ breed }}"?</p>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel"
         onclick="window.location='{% url 'cats:breed_list' %}';return false">
</form>
{% endblock content %}

cats/templates/cats/breed_form.html
{% extends 'base.html' %}

{% block title %}Add Breed{% endblock %}
{% block content %}
<h1>Add Breed</h1>
<form method="post">
  {% csrf_token %}
  <table>{{ form.as_table }}</table>
  <input type="submit" value="Submit">
  <input type="submit" value="Cancel"
         onclick="window.location='{% url 'cats:cat_list' %}';return false">
</form>
{% endblock content %}

cats/templates/cats/breed_list.html
{% extends 'base.html' %}

{% block title %}Breed list{% endblock %}
{% block content %}
<h1>Breed list</h1>
<ul>
  {% for breed in breed_list %}
  <li>
    {{ breed }}
    (<a href="{% url 'cats:breed_update' breed.id %}">Update</a>
    | <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
  </li>
  {% empty %}
  No breeds yet
  {% endfor %}
</ul>
<p><a href="{% url 'cats:breed_create' %}">Add breed</a> <a href="{% url 'cats:breed_list' %}">View breeds</a></p>
<p><a href="{% url 'cats:cat_list' %}">Back to cats</a></p>
{% endblock content %}

cats/templates/cats/cat_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Cat{% endblock %}
{% block content %}
<h1>Confirm delete</h1>
<p>Do you really want to delete cat "{{ cat }}"?</p>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel"
         onclick="window.location='{% url 'cats:cat_list' %}';return !1">
</form>
{% endblock content %}

cats/templates/cats/cat_form.html
{% extends 'base.html' %}

{% block title %}Add Cat{% endblock %}
{% block content %}
<h1>Add Cat</h1>
<form method="post">
  {% csrf_token %}
  <table>{{ form.as_table }}</table>
  <input type="submit" value="Submit">
  <input type="submit" value="Cancel"
         onclick="window.location='{% url 'cats:cat_list' %}';return !1">
</form>
{% endblock content %}

cats/templates/cats/cat_list.html
{% extends 'base.html' %}

{% block title %}Cat List{% endblock %}
{% block content %}
<h1>Cat List</h1>
<ul>
  {% for cat in cat_list %}
  <li><p>
    {{ cat.nickname }} ({{ cat.breed }})
    (<a href="{% url 'cats:cat_update' cat.id %}">Update</a>
    | <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>)
    <br />
    {{ cat.foods }} ({{ cat.weight }} kg)
  </p></li>
  {% empty %}
  There are no cats in the library
  {% endfor %}
</ul>
<p><a href="{% url 'cats:cat_create' %}">Add a cat</a></p>
<p>
  <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) |
  <a href="{% url 'cats:breed_create' %}">Add a breed</a>
</p>
{% endblock content %}