ads/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import *

app_name = 'ads'
urlpatterns = [
    path('ads/', AdListView.as_view(), name='index'),
    path('ad/create', AdCreateView.as_view(), name='create'),
    path('ad/<int:pk>/', AdDetailView.as_view(), name='detail'),
    path('ad/<int:pk>/update', AdUpdateView.as_view(), name='update'),
    path('ad/<int:pk>/delete', AdDeleteView.as_view(), name='delete'),
    path('ad_picture/<int:pk>', stream_picture, name='ad_picture'),
    path('ad/<int:pk>/comment', create_comment, name='comment_create'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/ads/'), name='index'),
    path('', include('ads.urls')),
    path('home/', TemplateView.as_view(template_name='home/main.html'),
        name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

ads/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models

User = get_user_model()


class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[
            MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    # Picture
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=255, null=True,
        help_text="The MIME Type of this file")

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(User, through='Comment',
            related_name='comments_owned')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be > 3 chars")]
    )
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.text) < 15:
            return self.text
        else:
            return f"{self.text[:11]} ..."

ads/forms.py
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile

from ads.models import Ad
from ads.humanize import naturalsize


class AdForm(forms.ModelForm):
    upload_limit = 2 << 10 << 10
    upload_limit_text = naturalsize(upload_limit)

    picture = forms.FileField(required=False,
            label=f"File to Upload <= {upload_limit_text}")
    upload_field_name = 'picture'

    class Meta:
        model = Ad
        fields = ['title', 'price', 'text', 'picture']  # picture is manual
    
    def clean(self):
        # Validate the size of picture
        cleaned_data = super().clean()
        picture = cleaned_data.get('picture')
        if picture is None:
            return
        if len(picture) > self.upload_limit:
            self.add_error('picture',
                    f"File must be < {self.upload_limit_text}")

    def save(self, commit=False):
        # Convert uploaded file to a picture
        instance = super().save(commit=False)
        
        f = instance.picture
        if isinstance(f, InMemoryUploadedFile):
            byte_array = f.read()
            instance.content_type = f.content_type
            instance.picture = byte_array

        if commit:
            instance.save()

        return instance

class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

ads/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import View

from ads.forms import AdForm, CommentForm
from ads.models import Ad, Comment
from ads.owner import OwnerListView, OwnerDetailView, OwnerDeleteView


class AdListView(OwnerListView):
    model = Ad


class AdDetailView(OwnerDetailView):
    model = Ad


class AdDetailView(View):
    template_name = 'ads/ad_detail.html'

    def get(self, request, pk: int):
        ad = Ad.objects.get(pk=pk)
        comments = Comment.objects.filter(ad=ad).order_by('-created_at')
        form = CommentForm()
        context = {
            'ad': ad,
            'comments': comments,
            'comment_form': form,
        }
        return render(request, self.template_name, context)


class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:index')
    
    def get(self, request, pk: int = None):
        form = AdForm()
        context = {'form': form}
        return render(request, self.template_name, context)
    
    def post(self, request, pk: int = None):
        form = AdForm(request.POST, request.FILES or None)

        if not form.is_valid():
            context = {'form': form}
            return render(request, self.template_name, context)

        # Add owner to the model before saving
        ad = form.save(commit=False)
        ad.owner = request.user
        ad.save()
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:index')

    def get(self, request, pk: int):
        ad = get_object_or_404(Ad, pk=pk, owner=request.user)
        form = AdForm(instance=ad)
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, pk: int):
        ad = get_object_or_404(Ad, pk=pk, owner=request.user)
        form = AdForm(request.POST, request.FILES or None, instance=ad)
        
        if not form.is_valid():
            context = {'form': form}
            return render(request, self.template_name, context)

        ad = form.save(commit=False)
        ad.save()
        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad
    success_url = reverse_lazy('ads:index')


def stream_picture(request, pk: int):
    ad = get_object_or_404(Ad, pk=pk)

    if not ad.content_type:
        raise Http404

    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response['Cache-Control'] = f'max-age={24*60*60}'
    response.write(ad.picture)
    return response


@login_required
def create_comment(request, pk: int):
    if request.method == 'get':
        return redirect('ads:detail', pk=pk)

    ad = get_object_or_404(Ad, pk=pk)
    text = request.POST.get('comment')
    if not text or not (3 <= len(text) <= 500):
        return redirect('ads:detail', pk=pk)

    comment = Comment(text=text, ad=ad, owner=request.user)
    comment.save()
    return redirect('ads:detail', pk=pk)


class CommentDeleteView(OwnerDeleteView):
    model = Comment

    def get_success_url(self):
        ad = self.object.ad_id
        return reverse('ads:detail', kwargs={'pk': ad})

ads/templates/ads/_navbar_content.html
{# opening ul is in importing template #}
  <li {% if request.get_full_path == ads %}class="active"{% endif %}>
    <a href="{{ ads }}">Ads</a>
  </li>

  {% if user.is_authenticated %}
  <li><a href="{% url 'ads:create' %}">Create Ad</a></li>
  <li><a href="#!" class="dropdown-trigger" data-target="{{ dropdown }}">
    Account<i class="material-icons right">arrow_drop_down</i>
    </a></li>
  {% else %}
  <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
  {% endif %}
</ul>
<ul id="{{ dropdown }}" class="dropdown-content">
  <li><a href="{% url 'logout' %}?next={{ request.path }}">Log out</a></li>
{# Oops, closing ul #}

ads/templates/ads/ad_confirm_delete.html
{% extends 'ads/base_navbar.html' %}

{% block title %}Confirm delete{% endblock %}
{% block content %}
{{ block.super }}

<div class="container">
  <h1>Confirm delete</h1>
  <p>Do you really want to delete ad {{ ad }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button class="btn red waves-effect waves-light" type="submit">Yes, delete.</button>
    <a class="btn-flat waves-effect" href="{% url 'ads:detail' ad.id %}">Cancel</a>
  </form>
</div>
{% endblock content %}

ads/templates/ads/ad_detail.html
{% extends 'ads/base_navbar.html' %}

{% load humanize %}
{% load materializecss %}
{% block title %}{{ ad }} detail {% endblock %}

{% block css %}
{{ block.super }}
<style>
.align-down {
  display: flex;
  align-items: bottom;
}
.responsive:not(.active) {
  /* not .active to display correctly when lightboxed */
  max-width: 100%;
  height: auto;
}
.flex { display: flex; }
.reverse { flex-direction: row-reverse; }
.flex-1 { flex: 1; }
.img-container { max-width: 40%; }
@media screen and (max-width: 599.8px) {
  .column-on-small { flex-direction: column; }
  .img-container {
    max-width: 100%;
    width: 100%;
    display: flex;
    justify-content: center;
  }
}

</style>
{% endblock css %}

{% block js %}
{{ block.super }}
<script>
$(document).ready(function() {
  $('.materialboxed').materialbox()
})
</script>
{% endblock js %}

{% block content %}
{{ block.super }}
<div class="container">
  <h1 class="">{{ ad.title }}</h1>
  <div class="flex reverse column-on-small">
    {% if ad.content_type %}
    <div class="img-container">
      <img class="materialboxed responsive" src="{% url 'ads:ad_picture' ad.id %}">
    </div>
    {% endif %}

    <div class="flex-1">
      {{ ad.text|linebreaks }}
      <p>Price: ${{ ad.price }}</p>
      {% if ad.owner == request.user %}
      <a class="btn-flat waves-effect" href="{% url 'ads:update' ad.id %}">
        <i class="material-icons">edit</i></a>
      <a class="btn-flat waves-effect" href="{% url 'ads:delete' ad.id %}">
        <i class="material-icons">delete</i></a>
      {% endif %}
    </div>
  </div>
  <form action="comment" method="post">
    {% csrf_token %}
    {{ comment_form|materializecss }}
    <button type="submit" class="btn waves-effect waves-light">Submit</button>
    <a class="btn-flat waves-effect" href="{% url 'ads:index' %}">Back to ads</a>
  </form>
  {% for comment in comments %}
  <p class="align-down">
    <span>{{ comment.text }} ({{ comment.created_at|naturaltime }})</span>
      {% if comment.owner == request.user %}
      <a href="{% url 'ads:comment_delete' comment.id %}"><i class="material-icons">delete</i></a>
      {% endif %}
  </p>
  {% endfor %}
  </div>
</div>

{% endblock content %}

ads/templates/ads/ad_form.html
{% extends 'ads/base_navbar.html' %}

{% load materializecss %}
{% block title %}Add/Update Ad{% endblock %}

{% block content %}
{{ block.super }}
<div class="container">
  <form method="post" enctype="multipart/form-data" id="upload_form">
    {% csrf_token %}
    <div class="row">{{ form|materializecss:"s12 l6" }}</div>
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="btn waves-effect waves-light">Submit</button>
    <a href="{% url 'ads:index' %}" class="btn-flat waves-effect">Back</button>
  </form>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script>
  const select = document.querySelector.bind(document)

  select("#upload_form").onsubmit = function() {
    console.log('Checking file size')
    if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = select('#id_{{ form.upload_field_name }}').files[0]

      if (file && file.size > {{ form.upload_limit }} ) {
        alert(`File ${file.name} of type ${file.type} must be < {{ form.upload_limit_text }}`)
        return false
      }
    }
  };
</script>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends 'ads/base_navbar.html' %}

{% block content %}
{{ block.super }}
<div class="container">
  <h1>Ads application</h1>
  <p>Welcome to the ads applciation. Here you can create ads and comment on them. Be sure not to
     miss new versions ;)
  </p>
  {% if ad_list %}
  <ul class="collection">
    {% for ad in ad_list %}
    <li class="collection-item">
      <a href="{% url 'ads:detail' ad.id %}">{{ ad.title }}</a>
      {% if request.user == ad.owner %}
      <div class="secondary-content">
        <a href="{% url 'ads:update' ad.id %}"><i class="material-icons">edit</i></a>
        <a href="{% url 'ads:delete' ad.id %}"><i class="material-icons">delete</i></a>
      </div>
      {% endif %}
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No ads yet.</p>
  {% endif %}
</div>
{% endblock content %}

ads/templates/ads/base_navbar.html
{% extends 'base.html' %}

{% block css %}
  {{ block.super }}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock css %}

{% block js %}
  {{ block.super }}
  <script>
    $(document).ready(function() {
      $('.sidenav').sidenav()
      $('.dropdown-trigger').dropdown()
    })
  </script>
{% endblock js %}

{% block content %}
{% url 'ads:index' as ads %}
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo" style="padding-left: 1em">ChuckList</a>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger">
      <i class="material-icons">menu</i>
    </a>
    <ul class="right hide-on-med-and-down">
      {% include 'ads/_navbar_content.html' with dropdown="drop-account" %}
    </ul>
  </div>
</nav>

<ul class="sidenav" id="nav-mobile"> 
  {% include 'ads/_navbar_content.html' with dropdown="drop-account-mobile" %}
</ul>

{% endblock content %}

ads/templates/ads/comment_confirm_delete.html
{% extends 'ads/base_navbar.html' %}

{% block title %}Confirm delete{% endblock %}
{% block content %}
{{ block.super }}

<div class="container">
  <h1>Confirm delete</h1>
  <p>Do you really want to delete comment {{ comment }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button class="btn red waves-effect waves-light" type="submit">Yes, delete.</button>
    <a class="btn-flat waves-effect" href="{% url 'ads:detail' comment.ad_id %}">Cancel</a>
  </form>
</div>
{% endblock content %}